### PR TITLE
Add license header to every file and add test to check that

### LINKED ISSUE #10: Add License
I haven't added a license yet.

Should we go with GPLv3?

### PR DESCRIPTION
**Pull request by nitori**
Closes #10

### CODE REVIEW

**Comment by FichteFoll** [comment]
Imo this should not go into the docstring but rather into comments.

**Comment by knitori** [comment]
Replaced docstring with comment. I'm not sure about the first line though. I didn't just want to simply state "Shanghai" everywhere, without some sort of info about what Shanghai (in short terms) is.

**Comment by FichteFoll** [comment]
`# This file is part of Shanghai, an asynchronous multi-server IRC bot.` ?

**Comment by nitori** [comment]
Used your suggestion

**Pull request merged**
